//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OxronNotifier.OxronApi {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OxronApiResultTown", Namespace="http://www.oxron.com/")]
    [System.SerializableAttribute()]
    public partial class OxronApiResultTown : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OxronNotifier.OxronApi.OxronApiValidation ValidationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OxronNotifier.OxronApi.OxronApiTown> TownsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public OxronNotifier.OxronApi.OxronApiValidation Validation {
            get {
                return this.ValidationField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationField, value) != true)) {
                    this.ValidationField = value;
                    this.RaisePropertyChanged("Validation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.Generic.List<OxronNotifier.OxronApi.OxronApiTown> Towns {
            get {
                return this.TownsField;
            }
            set {
                if ((object.ReferenceEquals(this.TownsField, value) != true)) {
                    this.TownsField = value;
                    this.RaisePropertyChanged("Towns");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OxronApiValidation", Namespace="http://www.oxron.com/")]
    [System.SerializableAttribute()]
    public partial class OxronApiValidation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsSuccessful {
            get {
                return this.IsSuccessfulField;
            }
            set {
                if ((this.IsSuccessfulField.Equals(value) != true)) {
                    this.IsSuccessfulField = value;
                    this.RaisePropertyChanged("IsSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OxronApiTown", Namespace="http://www.oxron.com/")]
    [System.SerializableAttribute()]
    public partial class OxronApiTown : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid TownIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int XField;
        
        private int YField;
        
        private bool UnderAttackField;
        
        private bool UnderAttackNaturalResourceField;
        
        private int PopulationField;
        
        private OxronNotifier.OxronApi.TownStatus TownStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid TownId {
            get {
                return this.TownIdField;
            }
            set {
                if ((this.TownIdField.Equals(value) != true)) {
                    this.TownIdField = value;
                    this.RaisePropertyChanged("TownId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool UnderAttack {
            get {
                return this.UnderAttackField;
            }
            set {
                if ((this.UnderAttackField.Equals(value) != true)) {
                    this.UnderAttackField = value;
                    this.RaisePropertyChanged("UnderAttack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool UnderAttackNaturalResource {
            get {
                return this.UnderAttackNaturalResourceField;
            }
            set {
                if ((this.UnderAttackNaturalResourceField.Equals(value) != true)) {
                    this.UnderAttackNaturalResourceField = value;
                    this.RaisePropertyChanged("UnderAttackNaturalResource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Population {
            get {
                return this.PopulationField;
            }
            set {
                if ((this.PopulationField.Equals(value) != true)) {
                    this.PopulationField = value;
                    this.RaisePropertyChanged("Population");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public OxronNotifier.OxronApi.TownStatus TownStatus {
            get {
                return this.TownStatusField;
            }
            set {
                if ((this.TownStatusField.Equals(value) != true)) {
                    this.TownStatusField = value;
                    this.RaisePropertyChanged("TownStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TownStatus", Namespace="http://www.oxron.com/")]
    public enum TownStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Town = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        City = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Capital = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OxronApiResultEvent", Namespace="http://www.oxron.com/")]
    [System.SerializableAttribute()]
    public partial class OxronApiResultEvent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OxronNotifier.OxronApi.OxronApiValidation ValidationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OxronNotifier.OxronApi.OxronApiEvent> EventsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public OxronNotifier.OxronApi.OxronApiValidation Validation {
            get {
                return this.ValidationField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationField, value) != true)) {
                    this.ValidationField = value;
                    this.RaisePropertyChanged("Validation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.Generic.List<OxronNotifier.OxronApi.OxronApiEvent> Events {
            get {
                return this.EventsField;
            }
            set {
                if ((object.ReferenceEquals(this.EventsField, value) != true)) {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OxronApiEvent", Namespace="http://www.oxron.com/")]
    [System.SerializableAttribute()]
    public partial class OxronApiEvent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private OxronNotifier.OxronApi.TownActionTypes TownActionTypeField;
        
        private int CountField;
        
        private int TimeLeftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToolTipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public OxronNotifier.OxronApi.TownActionTypes TownActionType {
            get {
                return this.TownActionTypeField;
            }
            set {
                if ((this.TownActionTypeField.Equals(value) != true)) {
                    this.TownActionTypeField = value;
                    this.RaisePropertyChanged("TownActionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int TimeLeft {
            get {
                return this.TimeLeftField;
            }
            set {
                if ((this.TimeLeftField.Equals(value) != true)) {
                    this.TimeLeftField = value;
                    this.RaisePropertyChanged("TimeLeft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ToolTip {
            get {
                return this.ToolTipField;
            }
            set {
                if ((object.ReferenceEquals(this.ToolTipField, value) != true)) {
                    this.ToolTipField = value;
                    this.RaisePropertyChanged("ToolTip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TownActionTypes", Namespace="http://www.oxron.com/")]
    public enum TownActionTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Research = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Construct = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HostileAtt = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HostileAttNR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reinforcement = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReinforcementNR = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OwnTroopsHome = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendReinforcement = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AttOnEnemies = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Explore = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spying = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Trade = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Settlement = 13,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.oxron.com/", ConfigurationName="OxronApi.OxronApiSoap")]
    public interface OxronApiSoap {
        
        // CODEGEN: Generating message contract since element name accountName from namespace http://www.oxron.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.oxron.com/GetTownList", ReplyAction="*")]
        OxronNotifier.OxronApi.GetTownListResponse GetTownList(OxronNotifier.OxronApi.GetTownListRequest request);
        
        // CODEGEN: Generating message contract since element name accountName from namespace http://www.oxron.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.oxron.com/GetTownActionList", ReplyAction="*")]
        OxronNotifier.OxronApi.GetTownActionListResponse GetTownActionList(OxronNotifier.OxronApi.GetTownActionListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTownListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTownList", Namespace="http://www.oxron.com/", Order=0)]
        public OxronNotifier.OxronApi.GetTownListRequestBody Body;
        
        public GetTownListRequest() {
        }
        
        public GetTownListRequest(OxronNotifier.OxronApi.GetTownListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oxron.com/")]
    public partial class GetTownListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid serverAuth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string accountName;
        
        public GetTownListRequestBody() {
        }
        
        public GetTownListRequestBody(System.Guid serverAuth, System.Guid apiKey, string accountName) {
            this.serverAuth = serverAuth;
            this.apiKey = apiKey;
            this.accountName = accountName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTownListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTownListResponse", Namespace="http://www.oxron.com/", Order=0)]
        public OxronNotifier.OxronApi.GetTownListResponseBody Body;
        
        public GetTownListResponse() {
        }
        
        public GetTownListResponse(OxronNotifier.OxronApi.GetTownListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oxron.com/")]
    public partial class GetTownListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OxronNotifier.OxronApi.OxronApiResultTown GetTownListResult;
        
        public GetTownListResponseBody() {
        }
        
        public GetTownListResponseBody(OxronNotifier.OxronApi.OxronApiResultTown GetTownListResult) {
            this.GetTownListResult = GetTownListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTownActionListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTownActionList", Namespace="http://www.oxron.com/", Order=0)]
        public OxronNotifier.OxronApi.GetTownActionListRequestBody Body;
        
        public GetTownActionListRequest() {
        }
        
        public GetTownActionListRequest(OxronNotifier.OxronApi.GetTownActionListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oxron.com/")]
    public partial class GetTownActionListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid serverAuth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string accountName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Guid townGuid;
        
        public GetTownActionListRequestBody() {
        }
        
        public GetTownActionListRequestBody(System.Guid serverAuth, System.Guid apiKey, string accountName, System.Guid townGuid) {
            this.serverAuth = serverAuth;
            this.apiKey = apiKey;
            this.accountName = accountName;
            this.townGuid = townGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTownActionListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTownActionListResponse", Namespace="http://www.oxron.com/", Order=0)]
        public OxronNotifier.OxronApi.GetTownActionListResponseBody Body;
        
        public GetTownActionListResponse() {
        }
        
        public GetTownActionListResponse(OxronNotifier.OxronApi.GetTownActionListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oxron.com/")]
    public partial class GetTownActionListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OxronNotifier.OxronApi.OxronApiResultEvent GetTownActionListResult;
        
        public GetTownActionListResponseBody() {
        }
        
        public GetTownActionListResponseBody(OxronNotifier.OxronApi.OxronApiResultEvent GetTownActionListResult) {
            this.GetTownActionListResult = GetTownActionListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OxronApiSoapChannel : OxronNotifier.OxronApi.OxronApiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OxronApiSoapClient : System.ServiceModel.ClientBase<OxronNotifier.OxronApi.OxronApiSoap>, OxronNotifier.OxronApi.OxronApiSoap {
        
        public OxronApiSoapClient() {
        }
        
        public OxronApiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OxronApiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OxronApiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OxronApiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OxronNotifier.OxronApi.GetTownListResponse OxronNotifier.OxronApi.OxronApiSoap.GetTownList(OxronNotifier.OxronApi.GetTownListRequest request) {
            return base.Channel.GetTownList(request);
        }
        
        public OxronNotifier.OxronApi.OxronApiResultTown GetTownList(System.Guid serverAuth, System.Guid apiKey, string accountName) {
            OxronNotifier.OxronApi.GetTownListRequest inValue = new OxronNotifier.OxronApi.GetTownListRequest();
            inValue.Body = new OxronNotifier.OxronApi.GetTownListRequestBody();
            inValue.Body.serverAuth = serverAuth;
            inValue.Body.apiKey = apiKey;
            inValue.Body.accountName = accountName;
            OxronNotifier.OxronApi.GetTownListResponse retVal = ((OxronNotifier.OxronApi.OxronApiSoap)(this)).GetTownList(inValue);
            return retVal.Body.GetTownListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OxronNotifier.OxronApi.GetTownActionListResponse OxronNotifier.OxronApi.OxronApiSoap.GetTownActionList(OxronNotifier.OxronApi.GetTownActionListRequest request) {
            return base.Channel.GetTownActionList(request);
        }
        
        public OxronNotifier.OxronApi.OxronApiResultEvent GetTownActionList(System.Guid serverAuth, System.Guid apiKey, string accountName, System.Guid townGuid) {
            OxronNotifier.OxronApi.GetTownActionListRequest inValue = new OxronNotifier.OxronApi.GetTownActionListRequest();
            inValue.Body = new OxronNotifier.OxronApi.GetTownActionListRequestBody();
            inValue.Body.serverAuth = serverAuth;
            inValue.Body.apiKey = apiKey;
            inValue.Body.accountName = accountName;
            inValue.Body.townGuid = townGuid;
            OxronNotifier.OxronApi.GetTownActionListResponse retVal = ((OxronNotifier.OxronApi.OxronApiSoap)(this)).GetTownActionList(inValue);
            return retVal.Body.GetTownActionListResult;
        }
    }
}
